### PR TITLE
Dropdown Component

### PR DESCRIPTION
**Pull request by brian-patrick-3**
## Summary

Added dropdown component with serachable and multi-select variants.

## ADO Story Link

https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1235200

## Notes

- Dropdown component
- Dropdown Option component
- Searchable variant
- Multi-Select variant
- Accessibility
  - Keyboard navigation
  - Screen reader assistance messages
  - Focus handling
  - aria and role tags

## Testing Instructions

Open the Deploy Preview and view the Dropdown and Forms sections. I'm fairly confident in the keyboard navigation and focus handling, but not super confident in the screen reader experience which I can't really test. Please be critical with this one.

## Checklist

- [x] Used Conventional Commit messages as outlined in the contributing guide.
- [x] Documented/updated all props, events, slots, parts, etc with JSDoc.
  - [x] Ran the `analyze` command to update Storybook docs.
- [x] Added/updated Stories with controls to cover all variants.
- [x] Added/updated a basic unit test, at least, for each component.
- [x] Added/updated the Figma link for the Story's Design tab.
- [x] Added any new component exports to the src/index.ts file

### CODE REVIEW

**Review by cunningham-kyndryl — APPROVED** [review]
Looks great!

**Review by maulik-thaker1 — APPROVED** [review]
LGTM

**Pull request merged**
